vrpn_client_node:
  ros__parameters:
    server: "192.168.2.5"
    port: 3883
    update_frequency: 100.0
    frame_id: "world"
    # Use the VRPN server's time, or the client's ROS time.
    use_server_time: false
    broadcast_tf: true
    # refresh_tracker_frequency > 0.0 auto-discovers all Motive rigid bodies.
    # No need to list tracker names manually.
    refresh_tracker_frequency: 1.0